config/routes.rb
Rails.application.routes.draw do
  resources :congress_people
  devise_for :users
  resources :bills
  get '/home', to: 'home#index'
  
  root to: "home#index"

  get '/about', to: 'about#index'
end

app/models/bill.rb
class Bill < ActiveRecord::Base
		belongs_to :congress_person
		has_many :bps, :dependent => :destroy
		has_many :committees, :dependent => :destroy
		has_many :sponsors, :dependent => :destroy
		has_many :cosponsors, :dependent => :destroy

		accepts_nested_attributes_for :bps, :reject_if => :all_blank, :allow_destroy => true
		accepts_nested_attributes_for :committees, :reject_if => :all_blank, :allow_destroy => true
		accepts_nested_attributes_for :sponsors, :reject_if => :all_blank, :allow_destroy => true
		accepts_nested_attributes_for :cosponsors, :reject_if => :all_blank, :allow_destroy => true
end

app/models/bp.rb
class Bp < ActiveRecord::Base
		belongs_to :bill
end

app/models/committee.rb
class Committee < ActiveRecord::Base
	belongs_to :bill
	has_many :congress_people
end

app/models/congress_person.rb
class CongressPerson < ActiveRecord::Base
	has_many :bills
	belongs_to :committee
	has_attached_file :image, styles: { medium: "400x400#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/cosponsor.rb
class Cosponsor < ActiveRecord::Base
	belongs_to :bill
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
	belongs_to :bill
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bill = Bill.all.order("created_at DESC")
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:bill_name, :stage, :prop_date, :summary, :bill_number, bps_attributes:[:id, :bp, :_destroy], committees_attributes:[:id, :committee, :_destory],
        sponsors_attributes:[:id, :sponsor, :_destory], cosponsors_attributes:[:id, :cosponsor, :_destory])
    end
end

app/controllers/congress_people_controller.rb
class CongressPeopleController < ApplicationController
  before_action :set_congress_person, only: [:show, :edit, :update, :destroy]

  # GET /congress_people
  # GET /congress_people.json
  def index
    @congress_people = CongressPerson.all
  end

  # GET /congress_people/1
  # GET /congress_people/1.json
  def show
  end

  # GET /congress_people/new
  def new
    @congress_person = CongressPerson.new
  end

  # GET /congress_people/1/edit
  def edit
  end

  # POST /congress_people
  # POST /congress_people.json
  def create
    @congress_person = CongressPerson.new(congress_person_params)

    respond_to do |format|
      if @congress_person.save
        format.html { redirect_to @congress_person, notice: 'Congress person was successfully created.' }
        format.json { render :show, status: :created, location: @congress_person }
      else
        format.html { render :new }
        format.json { render json: @congress_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /congress_people/1
  # PATCH/PUT /congress_people/1.json
  def update
    respond_to do |format|
      if @congress_person.update(congress_person_params)
        format.html { redirect_to @congress_person, notice: 'Congress person was successfully updated.' }
        format.json { render :show, status: :ok, location: @congress_person }
      else
        format.html { render :edit }
        format.json { render json: @congress_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /congress_people/1
  # DELETE /congress_people/1.json
  def destroy
    @congress_person.destroy
    respond_to do |format|
      format.html { redirect_to congress_people_url, notice: 'Congress person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_congress_person
      @congress_person = CongressPerson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def congress_person_params
      params.require(:congress_person).permit(:first_name, :last_name, :image, :party, :bio, :state, :position, :dob, :district, :birth_place, :current_city)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/congress_people_helper.rb
module CongressPeopleHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.haml
.container
	.about
		%h1 About Us
		%p Here at Bullet Point Laws we strive to deliver the public with unbias and easy to read synposis of bills in various stages of the bill making process. We believe that providing everyone with access to proposed bills we can promote the democratic process and get the public involved in the bill making process. We often hear that people do not vote because they are not sure what they are voting on, We want to change that. We want to get people invloved and help make this country better places for all citizens. 
		%p As part of our promise to stay unbias, we deliver the facts and only the facts. We have no commentary and do not promote or oppose any bill. We want to provide the facts and allow the public to decide what is best for themselves and their families. We provide education on how to make your voice heard and the best way to contact those who need to hear your voice. We also do not want you to take our word for it, we will provide copies of the bill in its current stage for you to view yourselve. 

app/views/bills/_bp_fields.html.haml
.form-inline.clearfix
	.row
		.nested-fields
			= f.input :bp,  placeholder: "Enter a bullet point", label: false, input_html: { class: "form-input form-control", style: 'width:80%;'}

			= link_to_remove_association "Remove", f, class: "form-control btn btn-secondary", style: 'height:20%; display:inline; float:right;' 

app/views/bills/_committee_fields.html.haml
.form-inline.clearfix
	.row
		.nested-fields
			= f.input :committee,  collection: ["Agriculture - House", "Appropriations - House", "Armed Services - House", "Armed Services - House", "Budget - House", "Education and the Workforce - House", "Energy and Commerce - House", "Ethics - House", "Financial Services - House", "Foreign Affairs - House", "Homeland Security - House", "House Adminisration - House", "Judiciary - House", "Natural Resources - House", "Oversight Government Reform - House", "Rules - House","Science, Space, and Technology - House", "Small Business - House", "Transportation and Infrastructure - House", "Veterns' Affaris - House", "Ways and Means - House", "Agriculture, Nutrition, and Forestry - Senate", "Appropriations - Senate", "Armed Services - Senate", "Banking, Housing, and Urban Affairs - Senate", "Budget - Senate", "Commerce, Science, and Transportation - Senate", "Energy and Natural Resources - Senate", "Environment and Public Works - Senate", "Finance - Senate", "Foreign Relations - Senate", "Health, Education, Labor, and Pensions - Senate", "Homeland Security and Governmental Affairs - Senate", "Judiciary - Senate", "Rules and Administration - Senate", "Small Business and Entrepreneurship - Senate", "Veterans' Affairs - Senate" ], input_html: { class: "form-control form-input" }

			%span.input-group-btn
				= link_to_remove_association "Remove", f, class: "form-control btn btn-secondary"

app/views/bills/_cosponsor.html.haml
- @bill.cosponsors.each do |cosponsor|
	%tr
		%td= cosponsor.cosponsor 

app/views/bills/_empty_table_partial.html.haml
%tr.empty
  %td There are no cosponsors

app/views/bills/_form.html.haml
.simple_form
	= simple_form_for @bill,  html: { multipart: true } do |f|
		- if @bill.errors.any?
			#errors
				%p
					= @bill.errors.count
					Prevented this essential from saving
				%ul
					- @bill.errors.full_message.each do |msg|
						%li = msg
		.center
			.row-fluid
				.form
					= f.input :bill_number,  placeholder: "Bill Number", label: false, input_html: { class: 'form-control form-inline'}
			.row-fluid
				.form
					= f.input :bill_name,  placeholder: "Bill Name", label: false, input_html: { class: 'form-control form-inline'}
			.row-fluid
				.form
					= f.input :summary,  placeholder: "Summary", label: false, input_html: { class: 'form-control form-inline'}
			
			.row-fluid
				.col-md-4
				= f.input :prop_date,  placeholder: "Proposed Date", label: false, input_html: { class: 'form-control form-inline'}
			.row-fluid
				.col-md-12
					.input-group
						%h3 Commitees
						#committees-form
							= f.simple_fields_for :committees do |committee|
								= render 'committee_fields', f: committee
							.links
							= link_to_add_association 'Add Committee', f, :committees, class: 'btn btn-secondary add-button'
			
			.row-fluid
				.col-md-12
					= f.input :stage, collection: ["Pending", "Signed", "Vetoed"], input_html: { class: "form-control form-input" }
			
			.row-fluid
				.col-md-12
					%h3 Bullet Points
					#bps-form
						= f.simple_fields_for :bps do |bp|
							= render 'bp_fields', f: bp
						.links
						= link_to_add_association 'Add Bp', f, :bps, class: 'btn btn-secondary add-button'

			.row-fluid
				.col-md-12
					%h3 Sponsor
					#sponsors-form
						= f.simple_fields_for :sponsors do |sponsor|
							= render 'sponsor_fields', f: sponsor
						.links
						= link_to_add_association 'Add Sponsor', f, :sponsors, class: 'btn btn-secondary add-button'

			.row-fluid
				.col-md-12
					%h3 Cosponsor
					#cosponsors-form
						= f.simple_fields_for :cosponsors do |cosponsor|
							= render 'cosponsor_fields', f: cosponsor
						.links
						= link_to_add_association 'Add Coponsor', f, :cosponsors, class: 'btn btn-secondary add-button'




			= f.button :submit, class: 'btn btn-primary'

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.haml
- @bill.each_slice(3) do |bills|
  .row
    - bills.each do |bill|
      .col-md-4
        .bill
          %h2= link_to bill.bill_name, bill
          %h5= bill.stage
          %h5= bill.prop_date.strftime("%D")

app/views/bills/new.html.erb
<h1 id="new-bill">New Bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.haml
.row
	= link_to "Edit", edit_bill_path, class: "btn btn-secondary"

.row
	.name
		%h1.bill= @bill.bill_number + " - " + @bill.bill_name
	%p.date= "Date Instroduced: " + @bill.prop_date.strftime("%D")


.white
	.row{:id => "Sponsor-Block"}
		.col-md-8
			.row
				#sponsors
					%h6 
						%strong
							Sponsor(s):
						- @bill.sponsors.each do |sponsor|
							%ul
								%li= sponsor.sponsor
				#committee
					%h6 
						%strong
							Committee(s):
						- @bill.committees.each do |committee|
							%ul
								%li= committee.committee

			.row
				#bp
				%h6

					%strong
						Bullet Points:
				.bp
					- @bill.bps.each do |bp|
						%ul
							%li= bp.bp



		.col-md-4
		#cosponsors
			%h6 
				%strong
					Cosponsor(s):
			%table.table.table-hover
				= render(@bill.cosponsors) || render('empty_table_partial')



	.row
		.col-md-12
			#summary
			%h4 
				%strong
					Summary
			%p= @bill.summary

app/views/congress_people/_form.html.haml
.simple_form
	= simple_form_for @congress_person,  html: { multipart: true } do |f|
		- if @congress_person.errors.any?
			#errors
				%p
					= @congress_person.errors.count
					Prevented this essential from saving
				%ul
					- @congress_person.errors.full_message.each do |msg|
						%li = msg
		.center
			.row-fluid
				.form
					.col-md-12
						= f.input :image,  placeholder: "Image", label: false, input_html: { class: 'form-control'}
			.row-fluid
				.form
					.col-md-12
						= f.input :position, collection: ["Senator", "Representive"], input_html: { class: "form-control form-input" }
				.form
					.col-md-12
						= f.input :first_name,  placeholder: "First Name", label: false, input_html: { class: 'form-control form-inline'}
				.form
					.col-md-12
						= f.input :last_name,  placeholder: "Last Name", label: false, input_html: { class: 'form-control form-inline'}
			.row-fluid
				.form
					= f.input :state, collection: ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MS", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"], input_html: { class: "form-control form-input" }
			.row-fluid
				.form
					= f.input :bio,  placeholder: "Bio", label: false, input_html: { class: 'form-control form-inline'}
			.row-fluid
				.form
					= f.input :party, collection: ["Republican", "Democrat","Independant"], input_html: { class: "form-control form-input" }
			.row-fluid
				.col-md-4
				%h5 DOB
				= f.input :dob,  placeholder: "DOB", label: false, input_html: { class: 'form-control form-inline'}

			.row-fluid
				.form
					.col-md-12
						= f.input :district, collection: 1..53, input_html: { class: "form-control form-input" }
				.form
					.col-md-12
						= f.input :birth_place,  placeholder: "Birth Place", label: false, input_html: { class: 'form-control form-inline'}
				.form
					.col-md-12
						= f.input :current_city,  placeholder: "Current City", label: false, input_html: { class: 'form-control form-inline'}





			= f.button :submit, class: 'btn btn-primary'

app/views/congress_people/edit.html.haml
<h1>Editing Congress Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @congress_person %> |
<%= link_to 'Back', congress_people_path %>

app/views/congress_people/index.html.haml
<p id="notice"><%= notice %></p>

<h1>Listing Congress People</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @congress_people.each do |congress_person| %>
      <tr>
        <td><%= link_to 'Show', congress_person %></td>
        <td><%= link_to 'Edit', edit_congress_person_path(congress_person) %></td>
        <td><%= link_to 'Destroy', congress_person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Congress person', new_congress_person_path %>

app/views/congress_people/new.html.erb
<h1>New Congress Person</h1>

<%= render 'form' %>

<%= link_to 'Back', congress_people_path %>

app/views/congress_people/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_congress_person_path(@congress_person) %> |
<%= link_to 'Back', congress_people_path %>

app/views/cosponsors/_cosponsor.html.haml
- @bill.cosponsors.each do |cosponsor|
	%tr
		%td= cosponsor.cosponsor 

app/views/home/index.html.haml
This is the home page

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Bullet Point Bills
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	%link{:href => "https://fonts.googleapis.com/cssfamily=Cinzel:400,700,900|Playfair+Display+SC:400,700,900", :rel => "stylesheet"}/
	= csrf_meta_tags
%body
	- if user_signed_in?
		%a{:name => "top"}
		%nav.navbar.navbar-toggleable-sm.navbar-light.bg-faded{:style => "background-color: white"}
			%a.navbar-brand{:href => "#"}
				%img.d-inline-block.align-top{:alt => "", :height => "30", :src => "#{asset_path( 'logo_placeholder.png' )}", :width => "100"}/
				Bootstrap
			%ul.nav.nav-tabs
				%li.nav-item
					%a.nav-link{:href => "/congress_people"} Members Of Congress
				%li.nav-item
					%a.nav-link{:href => "/bills/new"} New Bill
				#bn
					%li.nav-item
						%a.nav-link{:href => "/bills"} Bills
				%li.nav-item
					%a.nav-link{:href => "/about"} About Us
				%li.nav-item
					%a.nav-link{:href => "/congress_people/new"} New Congress Person
			
			%ul.nav.pull-right
				%li
					=  link_to "Sign Out",destroy_user_session_path, method: :delete
					
	- else
		%a{:name => "top"}
		%nav.navbar.navbar-toggleable-sm.navbar-light.bg-faded{:style => "background-color: white"}
			%a.navbar-brand{:href => "#"}
				%img.d-inline-block.align-top{:alt => "", :height => "30", :src => "#{asset_path( 'logo_placeholder.png' )}", :width => "100"}/
				Bootstrap
			%ul.nav.nav-tabs
				%li.nav-item
					%a.nav-link{:href => "/congress_people"} Members of Congress 
				#bn
					%li.nav-item
						%a.nav-link{:href => "/bills"} Bills
				%li.nav-item
					%a.nav-link{:href => "/about"} About Us

	.container
		- flash.each do |name, msg|
			= content_tag :div, msg, class: "alert"

		= yield




	.container
		%footer
			.footer
				%ul
					%li
						.copy 
							&copy; 2016 basketCaseSoftWerks
					%li
						%a{:href => "mailto:someone@example.com"}
							About Us
					%li
						%a{:href => "mailto:someone@example.com"}
							Contact Us
					%li
						%a{:href => "mailto:someone@example.com"}
							Terms
					%li
						%a{:href => "#top"} Back to top